projects:
  default:
    schema: http://localhost:8000/___graphql
    documents:
      - './src/**/*.{ts,tsx}'
      - node_modules/gatsby-transformer-sharp/!(node_modules)/**/*.js
      - node_modules/gatsby-transformer-yaml/!(node_modules)/**/*.js
      - node_modules/gatsby-image/!(node_modules)/**/*.js
      - '!./src/types/generated-gatsby.ts'
    extensions:
      codegen:
        generates:
          ./src/types/generated-gatsby.ts:
            plugins:
              - typescript
              - typescript-operations
